default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args: ['--fix=auto']
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.4.0
    # rev: v5.4.0 will not change until we drop ansible 2.9
  hooks:
    - id: ansible-lint
      always_run: true
      pass_filenames: false
      # do not add file filters here as ansible-lint does not give reliable
      # results when called with individual files.
      # https://github.com/ansible/ansible-lint/issues/611
      verbose: true
      entry: ansible-lint --force-color -p -v .
      additional_dependencies:
        - 'ansible<2.10'
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
      # if you need to add more words to ignore, they are comme separated
      # e.g. [-L, 'lod,foo']
      args: [-L, 'lod']
