default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args: ['--fix=auto']
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.16.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
      # if you need to add more words to ignore, they are comme separated
      # e.g. [-L, 'lod,foo']
      args: [-L, 'lod']
