#!/bin/bash

cd $(git rev-parse --show-toplevel)

for product in PgBouncer pgBackRest pgMonitor PostgreSQL HAProxy; do
    git grep -i $product | grep -P "(?=(?i)$product)(?!${product,,}|$product)"
done
