{
 "title": "Bloat Details",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "ccp_datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pgcluster",
    "label": "PGCluster",
    "query": {
     "query": "label_values(up{exp_type='pg'}, cluster_name)"
    }
   },
   {
    "name": "pgnodes",
    "label": "Node",
    "query": {
     "query": "label_values(up{exp_type='pg', cluster_name=\"[[pgcluster]]\"}, job)"
    }
   },
   {
    "name": "pgdatabase",
    "label": "PGDatabase",
    "query": {
     "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\"},dbname)"
    }
   },
   {
    "name": "schemaname",
    "query": {
     "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\",dbname=\"[[pgdatabase]]\"},schemaname)"
    }
   },
   {
    "name": "objectname",
    "query": {
     "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\",dbname=\"[[pgdatabase]]\",schemaname=\"[[schemaname]]\"}, objectname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Bloat %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\"})/sum(ccp_bloat_check_size_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\"})*100"
    }
   ]
  },
  {
   "title": "Bloat Per Table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=\"[[pgdatabase]]\", schemaname=\"[[schemaname]]\",objectname=\"[[objectname]]\"}",
     "legendFormat": "{{schemaname}}.{{objectname}}"
    }
   ]
  },
  {
   "title": "Top N Bloated Tables > 10kB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ccp_bloat_check_total_wasted_space_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=\"[[pgdatabase]]\"} > 10240",
     "legendFormat": "{{dbname}}.{{schemaname}}.{{objectname}}"
    }
   ]
  }
 ]
}