{
 "title": "Query Statistics (pg_stat_statements)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "ccp_datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pgcluster",
    "label": "PGCluster",
    "query": {
     "query": "label_values(up{exp_type='pg'}, cluster_name)"
    }
   },
   {
    "name": "pgnodes",
    "label": "Node",
    "query": {
     "query": "label_values(up{exp_type='pg', cluster_name=\"[[pgcluster]]\"}, job)"
    }
   },
   {
    "name": "pgdatabase",
    "label": "PGDatabase",
    "query": {
     "query": "label_values(ccp_pg_stat_statements_total_calls_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\"}, dbname) "
    }
   },
   {
    "name": "role",
    "label": "role",
    "query": {
     "query": "label_values(ccp_pg_stat_statements_total_calls_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\",dbname=~\"[[pgdatabase]]\"}, role) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Queries Executed (Lifetime)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_calls_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Query Runtime (Lifetime)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Rows Retrieved or Affected (Lifetime)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_row_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Query Mean Runtime (Lifetime)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(ccp_pg_stat_statements_total_mean_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Queries Executed (Time Range Est.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_calls_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Query Runtime (Time Range Est.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Total Rows Retrieved or Affected (Time Range Est.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(ccp_pg_stat_statements_total_row_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Query Executions (Calls) Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ccp_pg_stat_statements_total_calls_count{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"}[1m])",
     "legendFormat": "db: {{dbname}}, user: {{role}}"
    }
   ]
  },
  {
   "title": "Query Mean Runtime (Top N Lifetime)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_mean_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"}"
    }
   ]
  },
  {
   "title": "Query Max Runtime (Top N Lifetime)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_max_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"}"
    }
   ]
  },
  {
   "title": "Query Total Runtime (Top N Lifetime)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_total_exec_time_ms{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"}"
    }
   ]
  },
  {
   "title": "Query Total WAL Genterated (Bytes Lifetime)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_wal_bytes{cluster_name=\"[[pgcluster]]\", job=\"[[pgnodes]]\", dbname=~\"[[pgdatabase]]\", role=~\"[[role]]\"}"
    }
   ]
  }
 ]
}