# Simple example reference: https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml
global:
    smtp_smarthost: 'smtp.example.com:587'
    smtp_from: 'Alertmanager <abc@yahoo.com>'
    smtp_auth_username: '<username>'
    smtp_auth_password: '<password>'

# templates:
# - '/etc/alertmanager/template/*.tmpl'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'example@crunchydata.com'
    send_resolved: true

- name: 'pagerduty-dba'
  pagerduty_configs:
      - service_key: <RANDOMKEYSTUFF>

- name: 'pagerduty-sre'
  pagerduty_configs:
      - service_key: <RANDOMKEYSTUFF>

- name: 'dba-team'
  email_configs:
  - to: 'example-dba-team@crunchydata.com'
    send_resolved: true

- name: 'sre-team'
  email_configs:
  - to: 'example-sre-team@crunchydata.com'
    send_resolved: true


inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition of warning if the alertname for the same system and service is already critical
  equal: ['alertname', 'job', 'service']


route:
    receiver: default-receiver
    group_by: [severity, service, job, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 24h

    routes:
    - match_re:
        service: ^(postgresql|mysql|oracle)$
      receiver: dba-team
      # sub route to send critical dba alerts to pagerduty
      routes:
      - match:
          severity: critical
        receiver: pagerduty-dba

    - match:
        service: system
      receiver: sre-team
      # sub route to send critical sre alerts to pagerduty
      routes:
      - match:
          severity: critical
        receiver: pagerduty-sre




