{
 "title": "pg_stat_statements",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "label": "PGCluster",
    "query": "label_values(up{exp_type='pg'}, job)"
   },
   {
    "name": "dbname",
    "label": "dbname",
    "query": "label_values(ccp_pg_stat_statements_total_calls_count{job=~\"[[pgnodes]]\"}, dbname) "
   },
   {
    "name": "role",
    "label": "role",
    "query": "label_values(ccp_pg_stat_statements_total_calls_count{job=~\"[[pgnodes]]\",dbname=~\"[[dbname]]\"}, role) "
   }
  ]
 },
 "panels": [
  {
   "title": "Query Calls Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ccp_pg_stat_statements_total_calls_count{job=\"[[pgnodes]]\", dbname=~\"[[dbname]]\", role=~\"[[role]]\"}[1m])",
     "legendFormat": "db: {{dbname}}, user: {{role}}"
    }
   ]
  },
  {
   "title": "Mean Query Runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_mean_time_ms{job=\"[[pgnodes]]\", dbname=~\"[[dbname]]\", role=~\"[[role]]\"}"
    }
   ]
  },
  {
   "title": "Max Query Runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_max_time_ms{job=\"[[pgnodes]]\", dbname=~\"[[dbname]]\", role=~\"[[role]]\"}"
    }
   ]
  },
  {
   "title": "Total Query Runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ccp_pg_stat_statements_top_total_time_ms{job=\"[[pgnodes]]\", dbname=~\"[[dbname]]\", role=~\"[[role]]\"}"
    }
   ]
  }
 ]
}