{
 "title": "Golden Signals 4",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service_name", "label": "service_name", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "Saturation (pct used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_total{service=\"[[service_name]]\"}*100/ccp_connection_stats_max_connections{service=\"[[service_name]]\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "ccp_pvc_used{service=\"[[service_name]]\", mount=\"/pgdata\"}*100/ccp_pvc_size{service=\"[[service_name]]\",mount=\"/pgdata\"}",
     "legendFormat": "data disk"
    },
    {
     "expr": "ccp_pvc_used{service=\"[[service_name]]\", mount=\"/backrestrepo\"}*100/ccp_pvc_size{service=\"[[service_name]]\",mount=\"/backrestrepo\"}",
     "legendFormat": "backup disk"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{service=\"[[service_name]]\"}[1m])) + sum(irate(ccp_stat_database_xact_rollback{service=\"[[service_name]]\"}[1m]))",
     "legendFormat": "Transactions per minute"
    },
    {
     "expr": "sum(irate(ccp_query_count{service=\"[[service_name]]\"}[1m])) + sum(irate(ccp_query_count{service=\"[[service_name]]\"}[1m]))",
     "legendFormat": "Queries per minute"
    },
    {
     "expr": "ccp_connection_stats_active{service=\"[[service_name]]\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Errors",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_deadlocks{service=\"[[service_name]]\"}[1m]))",
     "legendFormat": "Deadlock "
    },
    {
     "expr": "sum(irate(ccp_stat_database_conflicts{service=\"[[service_name]]\"}[1m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "pg_exporter_last_scrape_error{service=\"[[service_name]]\"}",
     "legendFormat": "scrape error"
    },
    {
     "expr": "clamp_max(ccp_archive_command_status_seconds_since_last_fail{service=\"[[service_name]]\"},1)",
     "legendFormat": "archive error"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_max_query_time{service=\"[[service_name]]\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}