{
 "title": "PostgreSQL Service Health Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(pg_cluster)" },
   {
    "name": "role",
    "query": "label_values({pg_cluster=\"[[cluster]]\"},role)"
   }
  ]
 },
 "panels": [
  {
   "title": "Saturation (pct used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ccp_connection_stats_total{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"} / ccp_connection_stats_max_connections{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "100 - 100 * ccp_nodemx_data_disk_available_bytes{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"} / ccp_nodemx_data_disk_total_bytes{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Mount:{{mount_point}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(irate(ccp_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))\n+ sum(irate(ccp_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Transactions per minute"
    },
    {
     "expr": "ccp_connection_stats_active{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Errors",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_deadlocks{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Deadlock "
    },
    {
     "expr": "sum(irate(ccp_stat_database_conflicts{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "pg_exporter_last_scrape_error{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "scrape error"
    },
    {
     "expr": "clamp_max(ccp_archive_command_status_seconds_since_last_fail{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"},1)",
     "legendFormat": "archive error"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_max_query_time{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}