{
 "title": "Network Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "osnodes",
    "query": "label_values(up{exp_type='node'}, job)"
   },
   {
    "name": "network_device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"[[osnodes]]\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=~\"[[osnodes]]\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=~\"[[osnodes]]\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[3m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[3m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Utillization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[1m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[1m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[24h]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[24h]))"
    }
   ]
  },
  {
   "title": "Network Errors/Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[3m]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{device=~\"[[network_device]]\",job=~\"[[osnodes]]\"}[3m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_CurrEstab{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "established"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_ActiveOpens{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_PassiveOpens{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_EstabResets{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "estabResets"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_AttemptFails{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Udp_InDatagrams{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InErrors{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_OutDatagrams{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_NoPorts{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InCsumErrors{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_SndbufErrors{job=~\"[[osnodes]]\"}[5m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_nf_conntrack_entries_limit{job=~\"[[osnodes]]\"}) - sum(node_nf_conntrack_entries{job=~\"[[osnodes]]\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_nf_conntrack_entries_limit{job=~\"[[osnodes]]\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}