{
 "title": "Bloat Details",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "label": "PGCluster",
    "query": "label_values(up{exp_type='pg'}, job)"
   },
   {
    "name": "dbname",
    "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{job=~\"[[pgnodes]]\"},dbname)"
   },
   {
    "name": "schemaname",
    "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{job=\"[[pgnodes]]\",dbname=\"[[dbname]]\"},schemaname)"
   },
   {
    "name": "objectname",
    "query": "label_values(ccp_bloat_check_total_wasted_space_bytes{job=~\"[[pgnodes]]\",dbname=\"[[dbname]]\",schemaname=\"[[schemaname]]\"}, objectname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Bloat %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_bloat_check_total_wasted_space_bytes{job=~\"[[pgnodes]]\"})/sum(ccp_bloat_check_size_bytes{job=~\"[[pgnodes]]\"})*100"
    }
   ]
  },
  {
   "title": "Bloat Per Table",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ccp_bloat_check_total_wasted_space_bytes{job=~\"[[pgnodes]]\", dbname=\"[[dbname]]\", schemaname=\"[[schemaname]]\",objectname=\"[[objectname]]\"}",
     "legendFormat": "{{schemaname}}.{{objectname}}"
    }
   ]
  },
  {
   "title": "Top N Bloated Tables > 10kB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ccp_bloat_check_total_wasted_space_bytes{job=~\"[[pgnodes]]\", dbname=\"[[dbname]]\"} > 10240",
     "legendFormat": "{{dbname}}.{{schemaname}}.{{objectname}}"
    }
   ]
  }
 ]
}