###
#
# Copyright © 2017-2024 Crunchy Data Solutions, Inc. All Rights Reserved.
#
###

# config file version
apiVersion: 1

datasources:
  - name: PROMETHEUS
    uid: PDC1078F23EBDF0E5
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: True
    editable: False
    orgId: 1
    version: 1
